image:
  repository: kong/kong-gateway
  tag: 2.2-alpine
  pullSecrets:
  - kong-enterprise-edition-docker

enterprise:
  enabled: true
  license_secret: kong-enterprise-license
  portal:
    enabled: true
ingressController:
  enabled: false
proxy:
  http:
    enabled: true
    # nodePort: 32000
  tls:
    enabled: false
  type: ClusterIP
admin:
  enabled: true
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001
    # nodePort: 32001
  tls:
    enabled: false
  type: ClusterIP
manager:
  http:
    enabled: true
    servicePort: 8002
    containerPort: 8002
    # nodePort: 32002
  tls:
    enabled: false
  type: ClusterIP
env:
  database: postgres
  pg_user: kong
  pg_password: kong
  pg_port: 5432
  admin_listen: 0.0.0.0:8001, 0.0.0.0:32001
  admin_gui_flags: '{"IMMUNITY_ENABLED":true}'
  password:
    valueFrom:
      secretKeyRef:
        name: kong-admin-token-secret
        key: kong-admin-token
  enforce_rbac: "on"
  admin_gui_auth: basic-auth
  admin_gui_session_conf: '{"cookie_name":"admin_session","secret":"super-secret","cookie_secure":false,"storage":"kong"}'
  portal_auth: basic-auth
  portal_session_conf: '{"cookie_name":"portal_session","secret":"super-secret","cookie_secure":false,"storage":"kong"}'
  plugins: bundled,collector
postgresql:
  enabled: true
  postgresqlUsername: kong
  postgresqlPassword: kong
  postgresqlDatabase: kong
  nameOverride: kongdb
  service:
    port: 5432
  persistence:
    enabled: true
  volumePermissions:
    enabled: true
