image:
  repository: kong-docker-kong-brain-immunity-base.bintray.io/kong-brain-immunity
  tag: 1.1.0
  # repository: kong-docker-kong-brain-internal-builds.bintray.io/kong-brain
  # tag: latest

imagePullSecrets:
  - name: regcred

waitImage:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent


kong:
  host: my-kong-kong-admin
  port: "8001"

postgres:
  host: my-psql-postgresql
  port: 5432
  username: collector
  password: collector

redis:
  host: my-redis-master
  port: 6379
  password: redis

service:
  type: NodePort
  port: 5000

ingress:
  enabled: false
