image:
  repository: kong-docker-kong-brain-immunity-base.bintray.io/kong-brain-immunity
  tag: 1.1.0
  pullPolicy: IfNotPresent
  # repository: kong-docker-kong-brain-internal-builds.bintray.io/kong-brain
  # tag: latest

imagePullSecrets:
  - name: bintray-kong-brain-immunity

waitImage:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent


kong:
  host: my-kong-kong-admin
  port: "8001"

postgresql:
  enabled: true
  postgresqlUsername: collector
  postgresqlPassword: collector
  postgresqlDatabase: collector
  service:
    port: 5432

redis:
  enabled: true
  port: 6379
  password: redis

service:
  type: NodePort
  port: 5000

ingress:
  enabled: false
