{{- if .Values.exteralSecrets.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: kong-immunity-docker
spec:
  backendType: systemManager
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - key: {{ .Values.exteralSecrets.path }}
      name: .dockerconfigjson
{{- end }}
