image:
  repository: kong/immunity
  tag: 4.1.0
  pullPolicy: IfNotPresent

waitImage:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent

collector:
  containerPort: 5000
  # Set a nodePort which is available
  # nodePort: 31555
  service:
    type: ClusterIP
    port: 5000

postgresql:
  ## Set to false if bringing your own postgresql
  enabled: true
  postgresqlUsername: collector
  postgresqlPassword: collector
  postgresqlDatabase: collector
  service:
    port: 5432
    # host: collector-postgresql # uncomment if bringing your own postgresql
  persistence:
    enabled: true
  volumePermissions:
    enabled: true

redis:
  ## Set to false if bringing your own redis.
  enabled: true
  port: 6379
  password: redis
  # host: collector-redis-master # uncomment if bringing your own redis
  persistence:
    enabled: true
  volumePermissions:
    enabled: true

ingress:
  enabled: false

exteralSecrets:
  enabled: false
  path: /cloud.konghq.com/dockerhub/kongcloud/dockerconfigjson
