image:
  repository: kong/immunity
  tag: 4.1.0
  pullPolicy: IfNotPresent

waitImage:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent

# These parameters enable collector to resolve names in the alerts
kongAdmin:
  # Set this to the Kong Admin API hostname
  host: my-kong-kong-admin
  # Set this to the Kong Admin API port
  servicePort: 8001
  # Set this to the Kong Admin API protocol
  protocol: http
  # Set this to the Kong Admin API token / KONG_PASSWORD
  token:
    valueFrom:
      secretKeyRef:
        name: kong-admin-token-secret
        key: kong-admin-token
  # Set this to override the name of the secret above
  # existingSecret: kong-admin-token-secret

collector:
  containerPort: 5000
  # Set a nodePort which is available
  # nodePort: 31555
  service:
    type: ClusterIP
    port: 5000
  # Set this to the maximum number of requests to keep in the PostgreSQL database. Any requests over this number are cleaned out daily, starting from the oldest request.
  max_har_storage: 2000000
  # Set this to the number of allowed consecutive minutes of abnormal traffic, meaning that there are sudden unexpected traffic drops or increases, or the traffic pattern is suddenly erratic. If traffic remains abnormal past the set time limit, it triggers an alert.
  traffic_alert_min: 1

postgresql:
  ## Set to false if bringing your own postgresql
  enabled: true
  postgresqlUsername: collector
  postgresqlPassword: collector
  postgresqlDatabase: collector
  service:
    port: 5432
    # host: collector-postgresql # uncomment if bringing your own postgresql
  persistence:
    enabled: true
  volumePermissions:
    enabled: true

redis:
  ## Set to false if bringing your own redis.
  enabled: true
  port: 6379
  password: redis
  # host: collector-redis-master # uncomment if bringing your own redis
  persistence:
    enabled: true
  volumePermissions:
    enabled: true

ingress:
  enabled: false

exteralSecrets:
  enabled: false
  path: /cloud.konghq.com/dockerhub/kongcloud/dockerconfigjson
