apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app: celery-beat
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: celery-beat
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
        app: celery-beat
        release: "{{ .Release.Name }}"
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: celery-beat
        release: "{{ .Release.Name }}"
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
      - name: wait-for-postgres
        image: "{{ .Values.waitImage.repository }}:{{ .Values.waitImage.tag }}"
        imagePullPolicy: {{ .Values.waitImage.pullPolicy }}
        env:
        - name: COLLECTOR_PG_HOST
          value: "{{ .Values.postgres.host }}"
        - name: COLLECTOR_PG_PORT
          value: "{{ .Values.postgres.port }}"
        command: [ "/bin/sh", "-c", "until nc -zv $COLLECTOR_PG_HOST $COLLECTOR_PG_PORT -w1; do echo 'waiting for db'; sleep 1; done" ]
      containers:
      - args:
        - bash
        - -c
        - celery beat -l info -A collector.scheduler.celery
        env:
        - name: CELERY_BROKER_URL
          value: "redis://:{{ .Values.redis.password }}@{{ .Values.redis.host }}:{{ .Values.redis.port }}/0"
        - name: COLLECTOR_DISCARD
          value: "True"
        - name: FLASK_APP
          value: /collector
        - name: KONG_HOST
          value: {{ .Values.kong.host }}
        - name: KONG_PORT
          value: "{{ .Values.kong.port }}"
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/collector"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: celery-beat
        resources: {}
      restartPolicy: Always
status: {}
