apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: celery-worker
  name: celery-worker
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
        io.kompose.service: celery-worker
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: celery-worker
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - args:
        - bash
        - -c
        - while ! </dev/tcp/{{ .Values.postgres.host }}/5432; do sleep 1; done;  celery worker -l info -A collector.scheduler.celery --concurrency=1
        env:
        - name: CELERY_BROKER_URL
          value: {{ .Values.redis.uri }}
        - name: COLLECTOR_DISCARD
          value: "True"
        - name: FLASK_APP
          value: /collector
        - name: KONG_HOST
          value: {{ .Values.kong.host }}
        - name: KONG_PORT
          value: "{{ .Values.kong.port }}"
        - name: PYTHONPATH
          value: /collector
        - name: SQLALCHEMY_DATABASE_URI
          value: postgres://collector:collector@{{ .Values.postgres.host }}:5432/collector
        image: {{ .Values.image }}
        name: celery-worker
        resources: {}
      restartPolicy: Always
status: {}
