apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    io.kompose.service: celery-worker
  name: celery-worker
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
        io.kompose.service: celery-worker
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: celery-worker
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - args:
        - bash
        - -c
        - while ! </dev/tcp/{{ .Values.postgres.host }}/{{ .Values.postgres.port }}; do sleep 1; done;  celery worker -l info -A collector.scheduler.celery --concurrency=1
        env:
        - name: CELERY_BROKER_URL
          value: "redis://:{{ .Values.redis.password }}@{{ .Values.redis.host }}:{{ .Values.redis.port }}/0"
        - name: COLLECTOR_DISCARD
          value: "True"
        - name: FLASK_APP
          value: /collector
        - name: KONG_HOST
          value: {{ .Values.kong.host }}
        - name: KONG_PORT
          value: "{{ .Values.kong.port }}"
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/collector"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: celery-worker
        resources: {}
      restartPolicy: Always
status: {}
