apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kong-collectorapi.fullname" . }}
  annotations: {}
  creationTimestamp: null
  labels:
    io.kompose.service: collector
spec:
  replicas: 1
  selector:
    matchLabels:
        io.kompose.service: collector
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: collector
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - args:
        - bash
        - -c
        - while ! </dev/tcp/{{ .Values.postgres.host }}/{{ .Values.postgres.port }}; do sleep 1; done; flask db upgrade && /collector/run-collector.sh
        env:
        - name: CELERY_BROKER_URL
          value: {{ .Values.redis.uri }}
        - name: COLLECTOR_DISCARD
          value: "True"
        - name: FLASK_APP
          value: /collector
        - name: KONG_HOST
          value: {{ .Values.kong.host }}
        - name: KONG_PORT
          value: "{{ .Values.kong.port }}"
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgres://collector:collector@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/collector"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: collector
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
