apiVersion: v1
kind: Service
metadata:
  name: {{ include "kong-collectorapi.fullname" . }}
  annotations: {}
  creationTimestamp: null
  labels:
    {{- include "kong-collectorapi.metaLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "kong-collectorapi.metaLabels" . | nindent 4 }}
status:
  loadBalancer: {}
