apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kong-collectorapi.fullname" . }}
  annotations: {}
  creationTimestamp: null
  labels:
    {{- include "kong-collectorapi.metaLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kong-collectorapi.metaLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "kong-collectorapi.metaLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
      {{- include "kong-collectorapi.wait-for-db" . | nindent 6 }}
      {{- include "kong-collectorapi.wait-for-redis" . | nindent 6 }}
      {{- include "kong-collectorapi.wait-for-kong" . | nindent 6 }}
      containers:
      - name: collector
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - bash
        - -c
        - flask db upgrade && /collector/run-collector.sh
        envFrom:
        - configMapRef:
            name: collector-config
        env:
        - name: KONG_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: kong-admin-token-secret
              key: kong-admin-token
        ports:
        - containerPort: {{ .Values.collector.containerPort }}
        resources: {}
      - name: celery-worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - bash
        - -c
        - celery worker -l info -A collector.scheduler.celery --concurrency=1
        envFrom:
        - configMapRef:
            name: collector-config
        env:
        - name: KONG_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: kong-admin-token-secret
              key: kong-admin-token
      - name: celery-beat
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - bash
        - -c
        - celery beat -l info -A collector.scheduler.celery
        envFrom:
        - configMapRef:
            name: collector-config
        env:
        - name: KONG_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: kong-admin-token-secret
              key: kong-admin-token
        resources: {}
      restartPolicy: Always
status: {}
