apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: collector-database
  name: collector-database
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: collector-database
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: collector
        - name: POSTGRES_PASSWORD
          value: collector
        - name: POSTGRES_USER
          value: collector
        image: postgres:11
        name: collector-database
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
