apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: collector-database
  name: collector-database
spec:
  ports:
  - name: "5433"
    port: 5433
    targetPort: 5432
  selector:
    io.kompose.service: collector-database
status:
  loadBalancer: {}
