apiVersion: v1
kind: Service
metadata:
  name: {{ include "kong-collectorapi.fullname" . }}
  annotations: {}
  creationTimestamp: null
  labels:
    io.kompose.service: collector
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    io.kompose.service: collector
status:
  loadBalancer: {}
