apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  KONG_PROTOCOL: '{{ .Values.kongAdmin.protocol }}'
  KONG_HOST: '{{ .Values.kongAdmin.host }}'
  KONG_PORT: '{{ .Values.kongAdmin.servicePort }}'
  SQLALCHEMY_DATABASE_URI: 'postgres://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@{{ template "kong-collectorapi.postgresql.fullname" . }}:{{ .Values.postgresql.service.port }}/{{ .Values.postgresql.postgresqlDatabase }}'
  CELERY_BROKER_URL: 'redis://:{{ .Values.redis.password }}@{{ template "kong-collectorapi.redis.fullname" . }}:{{ .Values.redis.port }}/0'
  COLLECTOR_DISCARD: 'True'
  FLASK_APP: '/collector'
