apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: kong
  name: kong
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kong
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - args:
        - sh
        - -c
        - /wait-for db 5432 10 && /usr/local/bin/kong migrations bootstrap && /usr/local/bin/kong
          migrations up && /usr/local/bin/kong migrations finish && /usr/local/bin/kong
          start
        env:
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_GUI_AUTH
          value: basic-auth
        - name: KONG_ADMIN_GUI_LISTEN
          value: 0.0.0.0:8002
        - name: KONG_ADMIN_GUI_SESSION_CONF
          value: '{"secret":"Y29vbGJlYW5z","storage":"kong","cookie_secure":false}'
        - name: KONG_ADMIN_GUI_URL
          value: http://localhost:8002
        - name: KONG_ADMIN_LISTEN
          value: 0.0.0.0:8001
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_ENFORCE_RBAC
          value: "on"
        - name: KONG_LICENSE_DATA
          value: '{"license":{"signature":"1cc5269b6db833d4d04c6134784412d4594a316daec30a51ba93d72c236bb991d1cba8267e80cd51489a48fa754a7c289d947ba2745f6e1c02146b8ac80b82fd","payload":{"customer":"ABC
            Partner Company","license_creation_date":"2018-06-27","product_subscription":"Kong
            Only","admin_seats":"5","support_plan":"Premier","license_expiration_date":"2020-10-29","license_key":"00141000017OHUFAA4_a1V41000004wM2KEAU"},"version":1}}'
        - name: KONG_LOG_LEVEL
          value: info
        - name: KONG_PASSWORD
          value: handyshake
        - name: KONG_PG_DATABASE
          value: kong
        - name: KONG_PG_HOST
          value: db
        - name: KONG_PG_PASSWORD
          value: kong
        - name: KONG_PG_USER
          value: kong
        - name: KONG_PLUGINS
          value: collector
        - name: KONG_PORTAL
          value: "on"
        - name: KONG_PORTAL_AUTH
          value: basic-auth
        - name: KONG_PORTAL_GUI_URL
          value: http://localhost:8003
        - name: KONG_PORTAL_SESSION_CONF
          value: '{"cookie_name":"portal_session","secret":"super-secret","cookie_secure":false,"storage":"kong"}'
        - name: KONG_PROXY_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        - name: KONG_SMTP_MOCK
          value: "on"
        - name: KONG_VITALS
          value: "on"
        image: mashape/kong-enterprise:dev-master
        name: kong
        ports:
        - containerPort: 8000
        - containerPort: 8001
        - containerPort: 8002
        - containerPort: 8003
        - containerPort: 8004
        - containerPort: 8443
        - containerPort: 8444
        resources: {}
      restartPolicy: Always
status: {}
