apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: testendpoints
  name: testendpoints
spec:
  replicas: 1
  selector:
    matchLabels:
        io.kompose.service: testendpoints
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: testendpoints
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: {{ .Values.image }}
        name: testendpoints
        ports:
        - containerPort: 6000
        resources: {}
      restartPolicy: Always
status: {}
