apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: testendpoints
  name: testendpoints
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: testendpoints
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: kong-docker-kong-brain-internal-builds.bintray.io/kong-brain-test-endpoints:master
        name: testendpoints
        ports:
        - containerPort: 6000
        resources: {}
      restartPolicy: Always
status: {}
