apiVersion: v1
kind: Service
metadata:
  name: {{ include "kong-collectorapi.fullname" . }}
  annotations: {}
  creationTimestamp: null
  labels:
    {{- include "kong-collectorapi.metaLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.collector.service.type }}
  ports:
    - port: {{ .Values.collector.service.port }}
      {{- if (and (eq .Values.collector.service.type "NodePort") (not (empty .Values.collector.nodePort))) }}
      nodePort: {{ .Values.collector.nodePort }}
      {{- end }}
  selector:
    {{- include "kong-collectorapi.metaLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
status:
  loadBalancer: {}
