name: Lint and Test Charts

on:
  push:
    branches-ignore:
    - 'master'
  pull_request:
    branches:
    - '**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: lint
          config: ct.yaml

      - name: Create kind cluster and install
        env:
          KONG_LICENSE_DATA: ${{ secrets.LICENSE }}
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: |
          bash .github/workflows/e2e-kind.sh

