name: Lint and Test Charts

on:
  push:
    branches-ignore:
    - 'master'
  pull_request:
    branches:
    - '**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-alpha.3
        with:
          install_local_path_provisioner: true
        if: steps.lint.outputs.changed == 'true'

      - name: Add prerequisites
        run: |
          helm install my-kong kong/kong --version 1.3.0 -f kong-values.yaml
          kubectl create secret generic kong-admin-token-secret --from-literal=kong-admin-token=my-token
          docker pull kong-docker-kong-brain-immunity-base.bintray.io/kong-brain-immunity:1.2.1
          kind load docker-image kong-docker-kong-brain-immunity-base.bintray.io/kong-brain-immunity:1.2.1

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: install
