name: Lint and Test Charts

on:
  push:
    branches-ignore:
    - 'master'
  pull_request:
    branches:
    - '**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-alpha.3
        with:
          install_local_path_provisioner: true
        if: steps.lint.outputs.changed == 'true'

      - name: Run some sanity checks
        run: |
          kubectl create secret generic kong-admin-token-secret --from-literal=kong-admin-token=my-token
          kubectl create secret docker-registry bintray-kong-brain-immunity --docker-server=kong-docker-kong-brain-immunity-base.bintray.io --docker-username=${{ secrets.BINTRAY_USER }} --docker-password=${{ secrets.BINTRAY_KEY }}
          echo ${{ secrets.LICENSE }} >> license && kubectl create secret generic kong-enterprise-license --from-file=./license && rm -rf license

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: install
