name: Lint and Test Charts

on:
  push:
    branches-ignore:
    - 'master'
  pull_request:
    branches:
    - '**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run test
        run: |
          echo "I made a secret"
          echo "here is my secret though: ${{ secrets.SuperSecret }}""

