name: Lint and Test Charts

on:
  push:
    branches-ignore:
    - 'master'
  pull_request:
    branches:
    - '**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: lint

